// <auto-generated />
namespace MagazineStore.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-alpha3-20222")]
    public sealed partial class MudancaTabelaEnderecoToCliente : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MudancaTabelaEnderecoToCliente));
        
        string IMigrationMetadata.Id
        {
            get { return "201306081854182_MudancaTabelaEnderecoToCliente"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
